src/cbvpolls/urls.py
from django.urls import path

from cbvpolls.views import DetailView, IndexView, ResultsView, vote

app_name = "cbvpolls"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("<int:pk>/", DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", vote, name="vote"),
]

src/core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from core.views import CustomReleaseUserView, infoView

urlpatterns = [
    path("api-auth/", include("rest_framework.urls")),
    path("tinymce/", include("tinymce.urls")),
    path("admin/", admin.site.urls),
    path("hijack/release/", CustomReleaseUserView.as_view(), name="release"),
    path("hijack/", include("hijack.urls")),
    path("", include("polls.urls")),
    path("cbvpolls/", include("cbvpolls.urls")),
    # API schema and docs
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # API endpoints
    path("api/polls/", include("polls.api_urls")),
    # App version
    path("info/", infoView, name="info"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()

src/polls/urls.py
from django.urls import path

from polls.views import detail, index, results, vote

app_name = "polls"
urlpatterns = [
    # ex: /polls/
    path("", index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", vote, name="vote"),
]

src/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

src/cbvpolls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from polls.models import Choice, Question


class IndexView(generic.ListView):
    context_object_name = "latest_question_list"
    template_name = "cbvpolls/question_list.html"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "cbvpolls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "cbvpolls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "cbvpolls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("cbvpolls:results", args=(question.id,)))

src/core/views.py
import json

from django.conf import settings
from django.http import JsonResponse
from django.http.response import HttpResponseRedirect
from hijack.views import ReleaseUserView


def infoView(request, *args, **kwargs):
    with open(settings.BASE_DIR / "info.json", "r") as json_file:
        return JsonResponse(json.load(json_file))


class CustomReleaseUserView(ReleaseUserView):
    def post(self, request, *args, **kwargs):
        super().post(request, *args, **kwargs)
        return HttpResponseRedirect(settings.BASE_URL)

src/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question


def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

src/cbvpolls/templates/cbvpolls/detail.html
{% extends "base.html" %}

{% block content %}

    <form action="{% url 'cbvpolls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}
                <p>
                    <strong>{{ error_message }}</strong>
                </p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio"
                       name="choice"
                       id="choice{{ forloop.counter }}"
                       value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                <br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
{% endblock content %}

src/cbvpolls/templates/cbvpolls/question_list.html
{% extends "base.html" %}

{% block content %}

    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <a href="{% url 'cbvpolls:detail' question.id %}">{{ question.question_text }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock content %}

src/cbvpolls/templates/cbvpolls/results.html
{% extends "base.html" %}

{% block content %}

    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'cbvpolls:detail' question.id %}">Vote again?</a>
{% endblock content %}

src/polls/templates/polls/detail.html
{% extends "base.html" %}

{% block content %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}
                <p>
                    <strong>{{ error_message }}</strong>
                </p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio"
                       name="choice"
                       id="choice{{ forloop.counter }}"
                       value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                <br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
{% endblock content %}

src/polls/templates/polls/index.html
{% extends "base.html" %}

{% block content %}

    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock content %}

src/polls/templates/polls/results.html
{% extends "base.html" %}

{% block content %}

    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}

src/templates/_footer.html
{% load static %}
<footer class="mt-auto pt-2 pb-1 bg-dark text-white">
    <div class="container-xl">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-center">
            <div class="d-flex justify-content-center justify-content-sm-start">
                <img height="auto"
                     width="100px"
                     src="https://dcc.uchile.cl/static/images/base/logo_footer.svg"
                     alt="DCC" />
            </div>
            <div class="text-center text-sm-end pt-4 pt-sm-0 align-self-center">
                <div class="fw-bold">Diploma de Postítulo en Ingeniería de Softare</div>
                <div>Taller de Software 2025</div>
            </div>
        </div>
    </div>
</footer>

src/templates/_header.html
<nav class="navbar navbar-dark bg-dark">
    <div class="container-xl">
        <a class="navbar-brand" href="http://localhost:8000"><i class="bi bi-box-fill pe-2"></i>TDS Boilerplate</a>
        <form class="d-flex">
            <input class="form-control me-2"
                   type="search"
                   placeholder="Search"
                   aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</nav>

src/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>TDS | Boilerplate</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
              crossorigin="anonymous">
        {{ form.media }}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
                crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"
                integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.6/dist/htmx.min.js"
                integrity="sha384-Akqfrbj/HpNVo8k11SXBb6TlBWmXXlYQrCSqEWmyKJe+hDm3Z/B2WVG4smwBkRVm"
                crossorigin="anonymous"></script>
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    </head>
    <body class="d-flex flex-column min-vh-100">
        {% include "_header.html" %}
        <div class="pb-4 pt-2">
            <div class="container-xl">

                {% block content %}

                {% endblock content %}
            </div>
        </div>
        {% include "_footer.html" %}

        {% block scripts %}

        {% endblock scripts %}
    </body>
</html>